{% set name = "meshpy" %}
{% set uname = "MeshPy" %}
{% set version = "2022.1.3" %}
{% set sha256 = "a7158e31ece25fa6c6cebce9fd1e968157d661dc8769fb30ceba69c351478475" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ uname }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ uname[0] }}/{{ uname }}/{{ uname }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 4
  script:
    - {{ PYTHON }} -m pip install . --no-deps -v
    - echo src/cpp/tetgen-LICENSE >> doc/faq.rst
  skip: true  # [win and py<35]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - numpy
    - pybind11
    - setuptools
  run:
    - python
    - numpy

test:
  source_files:
    - test/*
  requires:
    - pytest
  commands:
    - pytest test
  imports:
    - meshpy

about:
  home: http://github.com/inducer/meshpy
  license: MIT AND LicenseRef-Proprietary-Triangle AND AGPL-3.0-or-later
  license_file: doc/faq.rst
  summary: Triangular and Tetrahedral Mesh Generator

  description: |

    MeshPy offers quality triangular and tetrahedral mesh generation for
    Python. Meshes of this type are mainly used in finite-element
    simulation codes, but also have many other applications ranging from
    computer graphics to robotics.

  doc_url: https://documen.tician.de/meshpy
  dev_url: https://github.com/inducer/meshpy

extra:
  recipe-maintainers:
    - inducer
    - isuruf
    - mwtoews
