appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: ETVxUukpS2ru++yE5OstlrU2ftlKwbsqv0H68Vl0vAF1oTrNAKjmqgwVbg4Wt2oVBrPOwgC88gRGXt7Hx9ZxYS1SSe9IcoZNuRP0ToCeGrTtivNzHHzjMGktDSSubQitXKMjncC+MHDosM4XAI8b6RX23vyjggQV3hIoekV5GaoL0uicaelysWlgJiQ+dwGfknRVwRo1/GB4Ui7dSr/QOPfIPGNqRFOpcYufLO/UtFpNTrQm1IasdubgxPSGflE6eFRhiS/IF5lmfogDPWcW6Y7t3SOUQsxHk/KUhuEGx7q844kOr6K5LmdrrRQohyXoX2LoyqVIMeUEpwwr7C9cH3+OIcIep4FuBVDOEEXEFBxe7vtI3EWUh7J4zl4zTVpl+h10Mq7jJfj0InV/ML7SL+kiMDbY+yFm48Uiltt5VRQXVZ1G5l8R0F/TJBOZr1OQR79O7v9QVsXFyqmfx8l5e/qNo84lkmPInJwL1q06cT334LOIK0oUlcRNO0oEKyw+kShIDuUMSzjbJzNVuWnEdZLeZ9E0SDki56QD5Vj7Y/nPHxL9EFfWvbPauKlIvrHgLlQiNgUdxXol7WpSsrWOsMczuaRAM27IpvRXDn1AD/r88eA2w8ud+j4WBwuod37xelacPshoQHcpp6bjaMtJnex7LulbFfdx8ziwMl0FVqU=}
